# publish-nuget.yml
name: Publish NuGet Package on Push to Main

on:
  push:
    branches:
      - main

jobs:
  Package:
    runs-on: ubuntu-latest

    env:
      NUGET_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      TEST: "false"
      CONFIG: Release
      VERSION: 1.0.${{ github.run_number }}
      NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PROJECT_FILE_PATH: src/Common.csproj

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0"
          source-url: ${{ env.NUGET_URL }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build \
          --no-restore \
          /p:VersionPrefix=${{ env.VERSION }} \
          --configuration ${{ env.CONFIG }} \
          -o out

      - name: Test
        if: ${{ env.TEST == 'true' }}
        run: dotnet test \
          --no-build \
          --configuration ${{ env.CONFIG }} \
          -o out

      - name: Package
        run: dotnet pack ${{ env.PROJECT_FILE_PATH }} \
          --no-build \
          --configuration ${{ env.CONFIG }} \
          /p:Version=${{ env.VERSION }} \
          -o packages

      - name: Publish NuGet
        # You may pin to the exact commit or the version.
        # uses: brandedoutcast/publish-nuget@c12b8546b67672ee38ac87bea491ac94a587f7cc
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: src/Common.csproj
          PACKAGE_NAME: WahineKai.Common
          NUGET_KEY: ${{ secrets.GITHUB_TOKEN }}
          NUGET_SOURCE: https://nuget.pkg.github.com/wahinekai/index.json}
